spring.application.name=FlightBooking
server.port=6996

spring.datasource.url=jdbc:mysql://localhost:3306/FlightBooking?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=FlightBookingJwtSecretKeyFlightBookingJwtSecretKey2026
app.jwt.expiration-ms=86400000

app.rabbitmq.queue=flight.booking.notification.queue
app.rabbitmq.exchange=flight.booking.exchange
app.rabbitmq.routing-key=flight.booking.notification

logging.level.com.example.FlightBooking=INFO
